"""init schema

Revision ID: 80626c44bffb
Revises: 
Create Date: 2026-06-15 22:57:49.522545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80626c44bffb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- Extensions (pgvector + full-text tiếng Việt) ---
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tag_type', sa.String(length=15), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['legal_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_legal_tags_status', 'legal_tags', ['status'], unique=False)
    op.create_index('idx_legal_tags_type', 'legal_tags', ['tag_type'], unique=False)
    op.create_table('source_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('ingest_status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_index('idx_source_files_status', 'source_files', ['ingest_status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('msg_type', sa.String(length=20), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('doc_level', sa.SmallInteger(), nullable=False),
    sa.Column('is_normative', sa.Boolean(), nullable=False),
    sa.Column('tier', sa.String(length=1), nullable=False),
    sa.Column('official_code', sa.String(length=50), nullable=True),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('domains', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('issuer_scope', sa.String(length=15), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw_markdown', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_domains', 'documents', ['domains'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_effective_date', 'documents', ['effective_date'], unique=False)
    op.create_index('idx_documents_issuer_scope', 'documents', ['issuer_scope'], unique=False)
    op.create_index('idx_documents_level', 'documents', ['doc_level'], unique=False)
    op.create_index('idx_documents_official_code', 'documents', ['official_code'], unique=False)
    op.create_index('idx_documents_province', 'documents', ['province'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_tier', 'documents', ['tier'], unique=False)
    op.create_index('idx_documents_type', 'documents', ['doc_type'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_file_id', sa.String(length=36), nullable=True),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_items_status', 'review_items', ['status'], unique=False)
    op.create_index('idx_review_items_type', 'review_items', ['item_type'], unique=False)
    op.create_table('document_tags',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['legal_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('parent_unit_id', sa.String(length=36), nullable=True),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('unit_no', sa.String(length=20), nullable=True),
    sa.Column('article_no', sa.String(length=20), nullable=True),
    sa.Column('clause_no', sa.String(length=20), nullable=True),
    sa.Column('point_label', sa.String(length=10), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('path_text', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('unit_status', sa.String(length=15), nullable=False),
    sa.Column('version_no', sa.SmallInteger(), nullable=False),
    sa.Column('supersedes_unit_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supersedes_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_units_document', 'units', ['document_id'], unique=False)
    op.create_index('idx_units_locator', 'units', ['document_id', 'article_no', 'clause_no', 'point_label'], unique=False)
    op.create_index('idx_units_order', 'units', ['document_id', 'order_index'], unique=False)
    op.create_index('idx_units_parent', 'units', ['parent_unit_id'], unique=False)
    op.create_index('idx_units_status', 'units', ['unit_status'], unique=False)
    op.create_index('idx_units_temporal', 'units', ['effective_from', 'effective_to'], unique=False)
    op.create_index('idx_units_type', 'units', ['unit_type'], unique=False)
    op.create_table('amendments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('new_unit_id', sa.String(length=36), nullable=False),
    sa.Column('old_unit_id', sa.String(length=36), nullable=True),
    sa.Column('old_ref_text', sa.Text(), nullable=True),
    sa.Column('amendment_type', sa.String(length=15), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=15), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolve_status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['new_unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['old_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_amendments_new', 'amendments', ['new_unit_id'], unique=False)
    op.create_index('idx_amendments_old', 'amendments', ['old_unit_id'], unique=False)
    op.create_index('idx_amendments_resolve', 'amendments', ['resolve_status'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('source_unit_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('unit_status', sa.String(length=15), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('legal_topics', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_dim', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_content_hash', 'chunks', ['content_hash'], unique=False)
    op.create_index('idx_chunks_document', 'chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_status', 'chunks', ['unit_status'], unique=False)
    op.create_index('idx_chunks_topics', 'chunks', ['legal_topics'], unique=False, postgresql_using='gin')
    op.create_index('idx_chunks_unit', 'chunks', ['source_unit_id'], unique=False)
    op.create_table('references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_unit_id', sa.String(length=36), nullable=False),
    sa.Column('to_unit_id', sa.String(length=36), nullable=True),
    sa.Column('to_ref_text', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=15), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('resolve_status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_unit_id'], ['units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_references_from', 'references', ['from_unit_id'], unique=False)
    op.create_index('idx_references_to', 'references', ['to_unit_id'], unique=False)
    op.create_index('idx_references_type', 'references', ['ref_type'], unique=False)
    # ### end Alembic commands ###

    # --- Raw SQL: phần ORM autogenerate KHÔNG sinh được ---

    # 1) Full-text search tiếng Việt: cột tsv tự cập nhật từ chunk_text.
    #    'simple' config + unaccent để khớp cả khi gõ không dấu.
    op.execute("ALTER TABLE chunks ADD COLUMN tsv tsvector")
    op.execute(
        """
        CREATE OR REPLACE FUNCTION chunks_tsv_update() RETURNS trigger AS $$
        BEGIN
            NEW.tsv := to_tsvector('simple', unaccent(coalesce(NEW.chunk_text, '')));
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_chunks_tsv
        BEFORE INSERT OR UPDATE OF chunk_text ON chunks
        FOR EACH ROW EXECUTE FUNCTION chunks_tsv_update();
        """
    )
    op.execute("CREATE INDEX idx_chunks_tsv ON chunks USING gin(tsv)")

    # 2) Vector search: HNSW trên embedding (cosine).
    op.execute(
        "CREATE INDEX idx_chunks_embedding_hnsw ON chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    # Raw SQL teardown (trước khi drop bảng chunks)
    op.execute("DROP INDEX IF EXISTS idx_chunks_embedding_hnsw")
    op.execute("DROP INDEX IF EXISTS idx_chunks_tsv")
    op.execute("DROP TRIGGER IF EXISTS trg_chunks_tsv ON chunks")
    op.execute("DROP FUNCTION IF EXISTS chunks_tsv_update()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_references_type', table_name='references')
    op.drop_index('idx_references_to', table_name='references')
    op.drop_index('idx_references_from', table_name='references')
    op.drop_table('references')
    op.drop_index('idx_chunks_unit', table_name='chunks')
    op.drop_index('idx_chunks_topics', table_name='chunks', postgresql_using='gin')
    op.drop_index('idx_chunks_status', table_name='chunks')
    op.drop_index('idx_chunks_document', table_name='chunks')
    op.drop_index('idx_chunks_content_hash', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('idx_amendments_resolve', table_name='amendments')
    op.drop_index('idx_amendments_old', table_name='amendments')
    op.drop_index('idx_amendments_new', table_name='amendments')
    op.drop_table('amendments')
    op.drop_index('idx_units_type', table_name='units')
    op.drop_index('idx_units_temporal', table_name='units')
    op.drop_index('idx_units_status', table_name='units')
    op.drop_index('idx_units_parent', table_name='units')
    op.drop_index('idx_units_order', table_name='units')
    op.drop_index('idx_units_locator', table_name='units')
    op.drop_index('idx_units_document', table_name='units')
    op.drop_table('units')
    op.drop_table('document_tags')
    op.drop_index('idx_review_items_type', table_name='review_items')
    op.drop_index('idx_review_items_status', table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_documents_official_code'), table_name='documents')
    op.drop_index('idx_documents_type', table_name='documents')
    op.drop_index('idx_documents_tier', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_province', table_name='documents')
    op.drop_index('idx_documents_official_code', table_name='documents')
    op.drop_index('idx_documents_level', table_name='documents')
    op.drop_index('idx_documents_issuer_scope', table_name='documents')
    op.drop_index('idx_documents_effective_date', table_name='documents')
    op.drop_index('idx_documents_domains', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    op.drop_index('idx_chat_messages_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_source_files_status', table_name='source_files')
    op.drop_table('source_files')
    op.drop_index('idx_legal_tags_type', table_name='legal_tags')
    op.drop_index('idx_legal_tags_status', table_name='legal_tags')
    op.drop_table('legal_tags')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
